app = "octodrop-platform-worker"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile.worker"

[processes]
  app = "python -m app.worker"

[[vm]]
  size = "performance-1x"
  memory = "2gb"
  cpus = 1
  memory_mb = 2048
